### ISSUE TITLE
Not working with typescript 2.8

### ISSUE THREAD

**Issue by farant** [Igorbek/typescript-plugin-styled-components#11]
I noticed the plugin stopped working (no modifications to emitted class names) after upgrading our project to typescript 2.8.

Using yarn to force `typescript-plugin-styled-components` to depend on typescript 2.8 seemed to fix the problem. In case anyone else runs into the problem, here's what we added to our package.json:

```
    "resolutions": {
        "typescript-plugin-styled-components/typescript": "^2.8.3"
    }
```

**Comment by Igorbek** [comment]
Version 0.0.6 just has been published where `typescript` is a peer dependency.
That must fix your issue. Let me know if it helps or not.

**Comment by farant** [comment]
Thanks! Looks like it fixed the problem

**Comment by winterbe** [comment]
Just tested with TS 2.8 and I can confirm that it works.

I also wanted to say "thank you" for your work publishing this project. 👏
