### ISSUE TITLE
NextJs+typescript

### ISSUE THREAD

**Issue by VienNguyen113** [Igorbek/typescript-plugin-styled-components#116]
My app using next-js+ typescript (next-babel-loader already support typescript). Is there any way to integrate this plugin with the next-babel-loader

**Comment by Igorbek** [comment]
Sorry for the late response. I will look into this in the next couple of days and tell you if it is possible to use the plugin.

**Comment by joshuatvernon** [comment]
@Igorbek did you ever figure this out?

**Comment by Igorbek** [comment]
Actually no. So NextJs uses babel for transpiling and not TS itself. Babel's loader just strips out the types using its native TS support but then transpiles by itself. This means the TS transformers are not involved in this process at all. This plugin is a TS transformer, so it cannot be integrated as such.
You may want to look at styled-component plugin for babel.

**Comment by jtomaszewski** [comment]
I submitted a small PR to include the above info in the README: https://github.com/Igorbek/typescript-plugin-styled-components/pull/209 . If merged, this issue probably can be closed as well.
