### ISSUE TITLE
Styled template string types ??

### ISSUE THREAD

**Issue by maitriyogin** [Igorbek/typescript-plugin-styled-components#18]
Hiya,
I'm currently trying to use typescript with a react native application and have run into a problem when using @types/styled-components...
When I try and use a styled component as a component
```
const LoginFormStyledView = styled.View`
  flex: 1;
`;
const LoginForm = () => <LoginFormStyledView />;
```
I get the following
```
[ts]
Type '{}' is not assignable to type 'Readonly<ThemedOuterStyledProps<View, any>>'.
  Property 'measure' is missing in type '{}'.
```
under the `<LoginFormStyledView />` component...
What do I need to do to get rid of this error?
Cheers,
Stephen.

**Comment by Igorbek** [comment]
Closing, feel free to reopen.
