### ISSUE TITLE
How get display name for styled component?

### ISSUE THREAD

**Issue by ravecat** [Igorbek/typescript-plugin-styled-components#19]
Thank you for transfer babel plugin functionality for TypeScript!

I followed step by step [instructions](https://github.com/Igorbek/typescript-plugin-styled-components#forked-process-configuration) and got that 

![example](https://preview.ibb.co/n7MhKz/example.png)

Can I get prefix `<fileName>__Wrapper` like babel plugin?

**Comment by Igorbek** [comment]
There's [an options object](https://github.com/Igorbek/typescript-plugin-styled-components#options) that you can pass to `createTransformer`:

```ts
const styledComponentsTransformer = createStyledComponentsTransformer({
  getDisplayName: (filename, bindingName) => getFilename(filename) + "_" + bindingName
});
```

**Comment by ravecat** [comment]
Thank you, @Igorbek !
