### ISSUE TITLE
Is it possible to disable vendor prefixes during development?

### ISSUE THREAD

**Issue by gitowiec** [Igorbek/typescript-plugin-styled-components#247]
I have asked this question on SO, so I don't want to repeat myself. But it was in regard of sole styled-components. When I was done with asking the question I realized that I rely on this `typescript-plugin-styled-components` library. I would like to ask this question also in regard of it. Is it possible to add configuration which will disable vendor prefixes? Here is my SO question https://stackoverflow.com/questions/62789170/how-to-disable-vendor-prefixes-in-styled-components-configuration
Best regards.

**Comment by Eoyo** [comment]
It would be nice to use StyleSheet Manager in Styled-components v5 plus.

**Comment by Igorbek** [comment]
It seems the question needs to be addressed to the core styled-components library, not this one. We do not provide this functionality.
