### ISSUE TITLE
Doesn't satisfy typescript@ˆ4.x

### ISSUE THREAD

**Issue by jmlavoier** [Igorbek/typescript-plugin-styled-components#342]
After the library has been installed, I've received a warning about typescript peer dependency. And after an `yarn check` I've received this error reported about that:

```bash
error "typescript-plugin-styled-components#typescript@^2.5.2 || ^3.0" doesn't satisfy found match of "typescript@4.1.3"
```

I've investigated and found this PR: [#312 - Support TypeScript 4](https://github.com/Igorbek/typescript-plugin-styled-components/pull/312). So I don't know whether this library is working properly or not with *TS 4*.

If it is really a problem, is there any solution by now?

**Comment by Igorbek** [comment]
It's now been fixed and released in https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.5.0
