### ISSUE TITLE
`minify` option breaks styles

### ISSUE THREAD

**Issue by Ky6uk** [Igorbek/typescript-plugin-styled-components#36]
I'm still investigating the code blocks but what I found for a quick look that option breaks animations through `transition` property and some paddings/margins. I will add code samples in the future.

**Comment by Igorbek** [comment]
Yes, please give some sample code.
I have tested on quite a big codebase (-30kb by minification) and didn't find issues so far.

**Comment by Ky6uk** [comment]
One of the problems is `keyframes`: https://github.com/Ky6uk/typescript-plugin-styled-components-36

**Comment by Igorbek** [comment]
Thank you, @Ky6uk 
It seems the issue is when a placeholder followed by spaces and then numeric values: `${smth} 2s` -> `${smth}2s`, which when it gets interpolated has no separation. I'll look into this shortly.

**Comment by Igorbek** [comment]
The fix has been release as of [1.4.1](https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.4.1).
