### ISSUE TITLE
Running two instances of styled components causes class name clashes

### ISSUE THREAD

**Issue by mcissel** [Igorbek/typescript-plugin-styled-components#381]
We need to be able to namespace each instance, like 
https://styled-components.com/docs/tooling#namespace

The problem is that hashing does not create unique classnames between instances. It's a known issue that was solved using the babel plugin. This plugin needs that as well, so we can use typescript.

**Comment by numonium** [comment]
I'm running into this issue on multiple sites that use `styled-components` 👍
