### ISSUE TITLE
Doesn't work with awesome-typescript-loader and transpileOnly: true

### ISSUE THREAD

**Issue by atellmer** [Igorbek/typescript-plugin-styled-components#4]
Hello!
Thanks for the plugin, but I have a some troubles with him.
He doesn't work with awesome-typescript-loader, when I set option transpileOnly: true.

node 8.2.1
webpack 3.0.0
awesome-typescript-loader 3.2.3

**Comment by Igorbek** [comment]
Hi, thanks for reporting.
Do you use it in watch mode or full bundling?
There's a known limitation that currently awe-t-l does not use transformers in the forked compilation (used in watch mode) see s-panferov/awesome-typescript-loader#423 and s-panferov/awesome-typescript-loader#447.

**Comment by Igorbek** [comment]
The feature has been implemented in https://github.com/s-panferov/awesome-typescript-loader/pull/531
I will update documentation how to use it.

**Comment by Igorbek** [comment]
`README` has been updated with the instructions.
