### ISSUE TITLE
Minify option removes some spaces with interpolations

### ISSUE THREAD

**Issue by Ky6uk** [Igorbek/typescript-plugin-styled-components#40]
`padding: 0 0 13px ${'50px'};` will be converted to `padding: 0 0 13px50px` with option `minify`.

**Comment by Igorbek** [comment]
@Ky6uk thank you for reporting these issues!
The fix is in #41 and will be released soon as 1.4.2

**Comment by Igorbek** [comment]
Fix has been released in [1.4.2](https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.4.2)
