### ISSUE TITLE
[moved] Usage question

### ISSUE THREAD

**Issue by Igorbek** [Igorbek/typescript-plugin-styled-components#42]
Is is possible to automatically assign a display name to styled-components or is it necessary to use .withConfig to set the displayName? I'm using typescript. How could I configure it to allow for automatic displayName assignment? Thanks

_Originally posted by @brianHolonis in https://github.com/Igorbek/typescript-plugin-styled-components/issues/24#issuecomment-482756545_

**Comment by Igorbek** [comment]
@brianHolonis `styled-components` cannot infer the name of the component by its own:

```ts
const MyComponentName = styled.div` ... `
```

from this styled-components only has information that it is a div element, but `MyComponentName` belongs to your code and is not passed down there.

This project (not `styled-components`, but this repo) is a tool that helps you just write code like you would write before and get component names automatically.

If you use this plugin, it will transform your code during compilation into

```ts
const MyComponentName = styled.div.withConfig({ displayName: 'MyComponentName' })` ... `
```

Please refer to the documentation in [README file](https://github.com/Igorbek/typescript-plugin-styled-components/blob/master/README.md) for information how to use the plugin.

**Comment by brianHolonis** [comment]
Thank you. I have it working. I noticed in jest tests if I output the component with debug ie console.log(component.debug()) I see <styled.div /> rather than the name. Can you tell me where I need to configure so that the DisplayName is used in the jest tests as well?

**Comment by Igorbek** [comment]
Closing as was no response from @brianHolonis
Please feel free to open a new issue and reference this.
