### ISSUE TITLE
[minify] adds spaces

### ISSUE THREAD

**Issue by mt-roberto** [Igorbek/typescript-plugin-styled-components#44]
In some cases minify feature adds some unwanted spaces.

Example:

origin: 

`transition: width ${(props: IProps) => props.speed}ms ease-in;`

result:

`transition: width 500 ms ease-in;`

**Comment by Igorbek** [comment]
Thank you for reporting @mt-roberto 
I will investigate the issue shortly.

**Comment by Igorbek** [comment]
Fixed by #45 and released as [version 1.4.3](https://github.com/Igorbek/typescript-plugin-styled-components/releases/tag/1.4.3).
