### ISSUE TITLE
Deprecate `extend` method on a component

### ISSUE THREAD

**Issue by Igorbek** [Igorbek/typescript-plugin-styled-components#48]
Reported by @Bdthomson in #33 
> I am running into the exact same issue with Backbone views such as this one:
> ```ts
> MyView.extend({
> ...
> })
> ```
> produces
> ```
> TypeError: MyView.extend.withConfig is not a function
> ```
> Edit:
> `.extend` was removed from styled-components in v4 ([styled-components/styled- components#1908](https://github.com/styled-components/styled-components/pull/1908)), is it possible to remove support for it in this plugin as well so you no longer have to maintain that transformation?
> 
> Put up a preliminary PR here - #47.

Suggested solution:
- make `extend` identifier configurable like other identifiers;
- set default value to an empty array;
- add readme/release notes with breaking change information and instructions to re-enable by providing settings.

**Comment by renatonouman** [comment]
Hey @Igorbek , it seems like the PR #47 is stale now. 
Mind if I pick up this issue and try to come up with a fix?

I saw your [comment](https://github.com/Igorbek/typescript-plugin-styled-components/pull/47#issuecomment-523077245) here and can work towards that.

**Comment by Igorbek** [comment]
I definitely don't mind, please go ahead @renatonouman if you want.

**Comment by renatonouman** [comment]
Thanks @Igorbek . I'll give it a go in the next couple of weeks.

**Comment by Igorbek** [comment]
Closed in #370
