### ISSUE TITLE
TypeScript version doesn't need to be pinned in peerDependencies

### ISSUE THREAD

**Issue by jussikinnula** [Igorbek/typescript-plugin-styled-components#593]
The rationale of pinning TypeScript version in peerDependencies should not be really required, since TypeScript versions usually don't create breakage for older code. It's possible that older TypeScript versions wouldn't work, so probably it would be safe to leave the peerDependency as minimum version.

**Comment by Igorbek** [comment]
I understand the sentiment, but we really had this issue with the breaking changes in TS API. We now released 3.0.0 with the updated TS version to support 4.8+/5.0+
